# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 231)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelNameServer = QtWidgets.QLabel(self.centralwidget)
        self.LabelNameServer.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LabelNameServer.setFont(font)
        self.LabelNameServer.setObjectName("LabelNameServer")
        self.lineEditNameServer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNameServer.setGeometry(QtCore.QRect(140, 30, 131, 20))
        self.lineEditNameServer.setObjectName("lineEditNameServer")
        self.LabelNameServer_2 = QtWidgets.QLabel(self.centralwidget)
        self.LabelNameServer_2.setGeometry(QtCore.QRect(20, 60, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LabelNameServer_2.setFont(font)
        self.LabelNameServer_2.setObjectName("LabelNameServer_2")
        self.lineEditNameServer_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNameServer_2.setGeometry(QtCore.QRect(140, 60, 131, 20))
        self.lineEditNameServer_2.setObjectName("lineEditNameServer_2")
        self.LabelNameServer_3 = QtWidgets.QLabel(self.centralwidget)
        self.LabelNameServer_3.setGeometry(QtCore.QRect(90, 90, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LabelNameServer_3.setFont(font)
        self.LabelNameServer_3.setObjectName("LabelNameServer_3")
        self.lineEditNameServer_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNameServer_3.setGeometry(QtCore.QRect(140, 90, 51, 20))
        self.lineEditNameServer_3.setObjectName("lineEditNameServer_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(240, 140, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 40, 91, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 432, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LabelNameServer.setText(_translate("MainWindow", "Назва сервера :"))
        self.LabelNameServer_2.setText(_translate("MainWindow", "IP адреса сервера :"))
        self.LabelNameServer_3.setText(_translate("MainWindow", "Порт :"))
        self.pushButton.setText(_translate("MainWindow", "Перевірити   \n"
" з\'єднання"))
