# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\monitor_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Monitor(object):

    

    def setupUi(self, Monitor):


        Monitor.setObjectName("Monitor")
        Monitor.setWindowModality(QtCore.Qt.NonModal)
        Monitor.resize(1200, 800)
        AppSize = Monitor.geometry()
        self.centralwidget = QtWidgets.QWidget(Monitor)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidgets = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgets.setGeometry(QtCore.QRect(10, 10, 1440, 800))
        self.tabWidgets.setObjectName("tabWidgets")
        self.tabWidgets.setIconSize(QtCore.QSize(40,40))
        self.tab_dashboard = QtWidgets.QWidget()
        self.tab_dashboard.setObjectName("tab_dashboard")
        self.GB_LS_TD = QtWidgets.QGroupBox(self.tab_dashboard)
        self.GB_LS_TD.setObjectName("GB_LS_TD")
        self.GB_LS_TD.setGeometry(QtCore.QRect(10, 10, 300, 800))
        self.GB_DB_TD = QtWidgets.QGroupBox(self.tab_dashboard)
        self.GB_DB_TD.setObjectName("GB_DB_TD")
        self.GB_DB_TD.setGeometry(QtCore.QRect(250, 10, 1000, 521))
        IconDashboard = QtGui.QIcon("img/dashboard.png")
        self.tabWidgets.addTab(self.tab_dashboard, IconDashboard, "")
        IconControl = QtGui.QIcon("img/control.png")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.tabWidgets.addTab(self.tab_control, IconControl, "")
        IconPreferences = QtGui.QIcon("img/preferences.png")
        self.tab_preferences = QtWidgets.QWidget()
        self.tab_preferences.setObjectName("tab_preferences")
        self.tabWidgets.addTab(self.tab_preferences, IconPreferences, "")
        self.GB_PS_TP = QtWidgets.QGroupBox(self.tab_preferences)
        self.GB_PS_TP.setObjectName("GB_PS_TP")
        self.GB_PS_TP.setGeometry(QtCore.QRect(10, 10, 360, 700))
        self.LLS = QtWidgets.QLabel(self.GB_PS_TP)
        self.LLS.setObjectName("LLS")
        self.LLS.setGeometry(QtCore.QRect(10, 90, 100, 13))
        self.GB_DB_TP = QtWidgets.QGroupBox(self.tab_preferences)
        self.GB_DB_TP.setObjectName("GB_PS_TP")
        self.GB_DB_TP.setGeometry(QtCore.QRect(665, 10, 500, 200))

        self.LabelHostServer = QtWidgets.QLabel(self.GB_DB_TP)
        self.LabelHostServer.setGeometry(QtCore.QRect(10, 30, 95, 16))
        self.LabelHostServer.setObjectName("LabelHostServer")
        self.lineEditHostServer = QtWidgets.QLineEdit(self.GB_DB_TP)
        self.lineEditHostServer.setGeometry(QtCore.QRect(105, 30, 150, 20))
        self.lineEditHostServer.setObjectName("lineEditHostServer")
        self.lineEditHostServer.setEnabled(False)

        self.LabelUserNameDB = QtWidgets.QLabel(self.GB_DB_TP)
        self.LabelUserNameDB.setGeometry(QtCore.QRect(10, 60, 95, 16))
        self.LabelUserNameDB.setObjectName("LabelUserNameBD")
        self.lineEditUserNameDB = QtWidgets.QLineEdit(self.GB_DB_TP)
        self.lineEditUserNameDB.setGeometry(QtCore.QRect(105, 60, 150, 20))
        self.lineEditUserNameDB.setObjectName("lineEditUserNameBD")
        self.lineEditUserNameDB.setEnabled(False)

        self.LabelPasswordDB = QtWidgets.QLabel(self.GB_DB_TP)
        self.LabelPasswordDB.setGeometry(QtCore.QRect(10, 90, 95, 16))
        self.LabelPasswordDB.setObjectName("LabelPasswordBD")
        self.lineEditPasswordDB = QtWidgets.QLineEdit(self.GB_DB_TP)
        self.lineEditPasswordDB.setGeometry(QtCore.QRect(105, 90, 150, 20))
        self.lineEditPasswordDB.setObjectName("lineEditPasswordBD")
        self.lineEditPasswordDB.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPasswordDB.setEnabled(False)

        self.LabelNameDB = QtWidgets.QLabel(self.GB_DB_TP)
        self.LabelNameDB.setGeometry(QtCore.QRect(10, 120, 95, 16))
        self.LabelNameDB.setObjectName("LabelUserNameBD")
        self.lineEditNameDB = QtWidgets.QLineEdit(self.GB_DB_TP)
        self.lineEditNameDB.setGeometry(QtCore.QRect(105, 120, 150, 20))
        self.lineEditNameDB.setObjectName("lineEditUserNameBD")
        self.lineEditNameDB.setEnabled(False)

        IconSaveButton = QtGui.QIcon("img/save_button.png")
        self.saveDbConnect = QtWidgets.QPushButton(self.GB_DB_TP)
        self.saveDbConnect.setIcon(IconSaveButton)
        self.saveDbConnect.setIconSize(QtCore.QSize(30,30))
        self.saveDbConnect.setObjectName("saveDbConnect")
        self.saveDbConnect.setToolTip("Зберегти")
        self.saveDbConnect.setGeometry(QtCore.QRect(10, 155, 40, 35))
        self.saveDbConnect.setEnabled(False)

        IconEditButton = QtGui.QIcon("img/edit_button.png")
        self.editDbConnect = QtWidgets.QPushButton(self.GB_DB_TP)
        self.editDbConnect.setIcon(IconEditButton)
        self.editDbConnect.setIconSize(QtCore.QSize(30,30))
        self.editDbConnect.setObjectName("editDbConnect")
        self.editDbConnect.setToolTip("Редагувати")
        self.editDbConnect.setGeometry(QtCore.QRect(62, 155, 40, 35))

        self.checkDbConnect = QtWidgets.QPushButton(self.GB_DB_TP)
        self.checkDbConnect.setObjectName("checkDbConnect")
        self.checkDbConnect.setToolTip("Перевірити  з\'єднання")
        self.checkDbConnect.setGeometry(QtCore.QRect(115, 155, 140, 35))
        self.checkDbConnect.setEnabled(False)


        IconAddServer = QtGui.QIcon("img/addServer.png")
        self.add_server = QtWidgets.QPushButton(self.GB_PS_TP)
        self.add_server.setIcon(IconAddServer)
        self.add_server.setIconSize(QtCore.QSize(40, 40))
        self.add_server.setContentsMargins(2, 2, 2, 5)
        self.add_server.setObjectName("addServer")
        self.add_server.setToolTip("Додати сервер")
        self.add_server.setGeometry(QtCore.QRect(10, 20, 50, 45))
        IconEditServer = QtGui.QIcon("img/editServer.png")
        self.edit_server = QtWidgets.QPushButton(self.GB_PS_TP)
        self.edit_server.setIcon(IconEditServer)
        self.edit_server.setIconSize(QtCore.QSize(40, 40))
        self.edit_server.setContentsMargins(2, 2, 2, 5)
        self.edit_server.setObjectName("editServer")
        self.edit_server.setToolTip("Редагувати сервер")
        self.edit_server.setGeometry(QtCore.QRect(65, 20, 50, 45))
        self.edit_server.setDisabled(True)
        IconDeleteServer = QtGui.QIcon("img/deleteServer.png")
        self.delete_server = QtWidgets.QPushButton(self.GB_PS_TP)
        self.delete_server.setIcon(IconDeleteServer)
        self.delete_server.setIconSize(QtCore.QSize(40, 40))
        self.delete_server.setContentsMargins(2, 2, 2, 5)
        self.delete_server.setObjectName("deleteServer")
        self.delete_server.setToolTip("Видалити сервер")
        self.delete_server.setGeometry(QtCore.QRect(120, 20, 50, 45))
        self.delete_server.setDisabled(True)

        Monitor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Monitor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 21))
        self.menubar.setObjectName("menubar")
        Monitor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Monitor)
        self.statusbar.setObjectName("statusbar")
        Monitor.setStatusBar(self.statusbar)

        self.retranslateUi(Monitor)
        self.tabWidgets.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Monitor)

    def retranslateUi(self, Monitor):
        _translate = QtCore.QCoreApplication.translate
        Monitor.setWindowTitle(_translate("Monitor", "MainWindow"))
        self.GB_LS_TD.setTitle(QtCore.QCoreApplication.translate("Monitor", "Список серверів", None))
        self.GB_PS_TP.setTitle(QtCore.QCoreApplication.translate("Monitor", "Налаштування серверів", None))
        self.GB_DB_TP.setTitle(QtCore.QCoreApplication.translate("Monitor", "Налаштування БД", None))
        self.LabelHostServer.setText(_translate("Monitor", "Адреса сервера :"))
        self.LabelUserNameDB.setText(_translate("Monitor", "Користувач :"))
        self.LabelPasswordDB.setText(_translate("Monitor", "Пароль :"))
        self.LabelNameDB.setText(_translate("Monitor", "Назва БД :"))
        self.checkDbConnect.setText(_translate("Monitor", "Перевірити   \n"
" з\'єднання"))

        self.GB_DB_TD.setTitle(QtCore.QCoreApplication.translate("Monitor", "Панель приборів", None))
        self.tabWidgets.setTabText(self.tabWidgets.indexOf(self.tab_dashboard), _translate("Monitor", "Моніторинг"))
        self.tabWidgets.setTabText(self.tabWidgets.indexOf(self.tab_control), _translate("Monitor", "Керування"))
        self.tabWidgets.setTabText(self.tabWidgets.indexOf(self.tab_preferences), _translate("Monitor", "Налаштування"))
